// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH-cd7c2sTtOH5TRes8xnlNacBMPAGs4Y',
    appId: '1:310457212150:web:a22969d9f4b4b2521de0d7',
    messagingSenderId: '310457212150',
    projectId: 'artkins-brew-crew',
    authDomain: 'artkins-brew-crew.firebaseapp.com',
    storageBucket: 'artkins-brew-crew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6x1PoP8N8d2WftCRwVWGzoW5ak11AkQ',
    appId: '1:310457212150:android:060075f87b7aaae71de0d7',
    messagingSenderId: '310457212150',
    projectId: 'artkins-brew-crew',
    storageBucket: 'artkins-brew-crew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOtiAEypWHph8BwyPQuuMbCUAw7xKH9ag',
    appId: '1:310457212150:ios:8842ba3a0d5eedc71de0d7',
    messagingSenderId: '310457212150',
    projectId: 'artkins-brew-crew',
    storageBucket: 'artkins-brew-crew.appspot.com',
    iosBundleId: 'com.artkins.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOtiAEypWHph8BwyPQuuMbCUAw7xKH9ag',
    appId: '1:310457212150:ios:8842ba3a0d5eedc71de0d7',
    messagingSenderId: '310457212150',
    projectId: 'artkins-brew-crew',
    storageBucket: 'artkins-brew-crew.appspot.com',
    iosBundleId: 'com.artkins.brewCrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH-cd7c2sTtOH5TRes8xnlNacBMPAGs4Y',
    appId: '1:310457212150:web:63c51aa2c793d6031de0d7',
    messagingSenderId: '310457212150',
    projectId: 'artkins-brew-crew',
    authDomain: 'artkins-brew-crew.firebaseapp.com',
    storageBucket: 'artkins-brew-crew.appspot.com',
  );
}
